### PR TITLE
chore: CRW-2456 set TargetFramework = net7.0

### PR DESCRIPTION
**Pull request by svor**
Set TargetFramework = net7.0

Screenshot/screencast of this PR

https://user-images.githubusercontent.com/1271546/203137041-77d22cfe-737f-4725-a2cb-2d845cd0f1fc.mp4

What issues does this PR fix or reference?
https://issues.redhat.com/browse/CRW-2456

### CODE REVIEW

**Review by nickboldt — APPROVED** [review]
see review on https://github.com/devspaces-samples/dotnet-web-simple/pull/8

**Comment by vitaliy-guliy** [comment]
I cannot say the changes in this pull request work properly on DS 3.2 (it's 3.2, but it should not matter as che-code and tooling are running in udi-rhel8:3.4)

If I do not install `muhammad-sammy.csharp` extension, at the first glance everything looks fine, no any errors.
But after installing the recommendation and analyzing the project, I got following

Screenshot from 2022-11-22 12-42-03

**Comment by vitaliy-guliy** [comment]
But it works fine on the dogfooding instance

Screenshot from 2022-11-22 13-04-29

**Comment by svor** [comment]
Maybe it somehow related DS 3.2, I've just tested it on DS 3.3 instance and it works:

https://user-images.githubusercontent.com/1271546/203308858-4115aa52-03c3-4548-9e68-f132941f7bbf.mp4

**Comment by vitaliy-guliy** [comment]
> Maybe it somehow related DS 3.2, I've just tested it on DS 3.3 instance and it works:
> 

Probably yes.
Then let's merge it.

**Pull request merged**
